// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';


function add(a, b) {
  return a + b | 0;
}

var result = 115;

console.log(result);

var message = "Hello, ReScript!";

console.log(message);

var new_var = "answer is 5";

console.log(new_var);

exports.add = add;
exports.result = result;
exports.message = message;
exports.new_var = new_var;
/*  Not a pure module */
